### ISSUE TITLE
Add rx.Single support

### ISSUE THREAD

**Issue by RoRoche** [florent37/Rx.Observe#2]
It would be enjoyable to have this feature (I use rx.Single very often).
Thanks!

**Comment by florent37** [comment]
you mean create @Single instead of @Observe ?

**Comment by florent37** [comment]
I can create it ;)

**Comment by RoRoche** [comment]
Yes, exactly, thanks a lot ;)

**Comment by florent37** [comment]
done, it's now compatible with Completable, Single and Flowable 👍
